[versions]
agp = "8.9.2"
androidLoadingDots = "1.3.2"
firebaseBom = "33.13.0"
fragmentKtx = "1.8.6"
gson = "2.11.0"
integrity = "1.4.0"
kotlin = "1.9.0"
coreKtx = "1.16.0"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.0"
material = "1.12.0"
activity = "1.10.1"
constraintlayout = "2.2.1"
photoviewVersion = "2.0.0"
pinviewVersion = "1.4.4"
securityCrypto = "1.1.0-alpha07"
uiDesktop = "1.7.0"
firebaseFirestore = "25.1.4"
firebaseDatabase = "21.0.0"
googleGmsGoogleServices = "4.4.2"
playServicesLocationVersion = "21.3.0"

[libraries]
android-loading-dots = { module = "com.github.razaghimahdi:Android-Loading-Dots", version.ref = "androidLoadingDots" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "fragmentKtx" }
androidx-security-crypto = { module = "androidx.security:security-crypto", version.ref = "securityCrypto" }
chaosleung-pinview = { module = "io.github.chaosleung:pinview", version.ref = "pinviewVersion" }
chrisbanes-photoview = { module = "com.github.chrisbanes:PhotoView", version.ref = "photoviewVersion" }
firebase-appcheck-playintegrity = { module = "com.google.firebase:firebase-appcheck-playintegrity" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
integrity = { module = "com.google.android.play:integrity", version.ref = "integrity" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
androidx-ui-desktop = { group = "androidx.compose.ui", name = "ui-desktop", version.ref = "uiDesktop" }
firebase-firestore = { group = "com.google.firebase", name = "firebase-firestore", version.ref = "firebaseFirestore" }
firebase-database = { group = "com.google.firebase", name = "firebase-database", version.ref = "firebaseDatabase" }
play-services-location = { group = "com.google.android.gms", name = "play-services-location", version.ref = "playServicesLocationVersion" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
google-gms-google-services = { id = "com.google.gms.google-services", version.ref = "googleGmsGoogleServices" }

